============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-5.4.2, py-1.5.2, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/ptisnovs/src/python/testing-in-python/pytest/average09
plugins: voluptuous-1.0.2, benchmark-3.2.3, cov-2.5.1
collecting ... collected 14 items

test_average.py::test_average_basic_3[values0-1] PASSED                  [  7%]
test_average.py::test_average_basic_3[values1-1.5] PASSED                [ 14%]
test_average.py::test_average_basic_3[values2-0.5] PASSED                [ 21%]
test_average.py::test_average_basic_3[values3-2.0] PASSED                [ 28%]
test_average.py::test_average_basic_3[values4-0.5] FAILED                [ 35%]
test_average.py::test_average_empty_list_1 PASSED                        [ 42%]
test_average.py::test_average_empty_list_2 PASSED                        [ 50%]
test_average_2.py::test_average_basic_3[values0-1] PASSED                [ 57%]
test_average_2.py::test_average_basic_3[values1-1.5] PASSED              [ 64%]
test_average_2.py::test_average_basic_3[values2-0.5] PASSED              [ 71%]
test_average_2.py::test_average_basic_3[values3-2.0] PASSED              [ 78%]
test_average_2.py::test_average_basic_3[values4-0.5] FAILED              [ 85%]
test_average_2.py::test_average_empty_list_1 PASSED                      [ 92%]
test_average_2.py::test_average_empty_list_2 PASSED                      [100%]

=================================== FAILURES ===================================
______________________ test_average_basic_3[values4-0.5] _______________________

values = (0, 10), expected = 0.5

    @pytest.mark.parametrize(
        "values,expected",
        [
            pytest.param(
                (1, 1), 1
            ),
            pytest.param(
                (1, 2), 1.5
            ),
            pytest.param(
                (0, 1), 0.5
            ),
            pytest.param(
                (1, 2, 3), 2.0
            ),
            pytest.param(
                (0, 10), 0.5
            ),
        ],
    )
    def test_average_basic_3(values, expected):
        """Otestování výpočtu průměru."""
        result = average(values)
>       assert result == expected, "Očekávaná hodnota {}, vráceno {}".format(expected, result)
E       AssertionError: Očekávaná hodnota 0.5, vráceno 5.0
E       assert 5.0 == 0.5
E         +5.0
E         -0.5

test_average.py:31: AssertionError
______________________ test_average_basic_3[values4-0.5] _______________________

values = (0, 10), expected = 0.5

    @pytest.mark.parametrize(
        "values,expected",
        (
            pytest.param(
                (1, 1), 1
            ),
            pytest.param(
                (1, 2), 1.5
            ),
            pytest.param(
                (0, 1), 0.5
            ),
            pytest.param(
                (1, 2, 3), 2.0
            ),
            pytest.param(
                (0, 10), 0.5
            ),
        ),
    )
    def test_average_basic_3(values, expected):
        """Otestování výpočtu průměru."""
        result = average(values)
>       assert result == expected, "Očekávaná hodnota {}, vráceno {}".format(expected, result)
E       AssertionError: Očekávaná hodnota 0.5, vráceno 5.0
E       assert 5.0 == 0.5
E         +5.0
E         -0.5

test_average_2.py:31: AssertionError
=========================== short test summary info ============================
FAILED test_average.py::test_average_basic_3[values4-0.5] - AssertionError: O...
FAILED test_average_2.py::test_average_basic_3[values4-0.5] - AssertionError:...
========================= 2 failed, 12 passed in 0.07s =========================
