============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-5.4.2, py-1.5.2, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/ptisnovs/src/python/testing-in-python/pytest/average14, inifile: pytest.ini
plugins: voluptuous-1.0.2, benchmark-3.2.3, cov-2.5.1
collecting ... collected 19 items

test_average.py::test_average_basic_1[values0-1] PASSED                  [  5%]
test_average.py::test_average_basic_1[values1-1.5] PASSED                [ 10%]
test_average.py::test_average_basic_1[values2-0.5] PASSED                [ 15%]
test_average.py::test_average_basic_1[values3-2.0] PASSED                [ 21%]
test_average.py::test_average_basic_1[values4-0.5] FAILED                [ 26%]
test_average.py::test_average_basic_2[1,1] PASSED                        [ 31%]
test_average.py::test_average_basic_2[1,2] PASSED                        [ 36%]
test_average.py::test_average_basic_2[0,1] PASSED                        [ 42%]
test_average.py::test_average_basic_2[1,2,3] PASSED                      [ 47%]
test_average.py::test_average_basic_2[0,10] FAILED                       [ 52%]
test_average.py::test_average_basic_3[values0-1] PASSED                  [ 57%]
test_average.py::test_average_basic_3[values1-1.5] PASSED                [ 63%]
test_average.py::test_average_basic_3[values2-0.5] PASSED                [ 68%]
test_average.py::test_average_basic_3[values3-2.0] PASSED                [ 73%]
test_average.py::test_average_basic_3[values4-0.5] FAILED                [ 78%]
test_average.py::test_average_basic_3[values5-0] FAILED                  [ 84%]
test_average.py::test_average_empty_list_1 PASSED                        [ 89%]
test_average.py::test_average_empty_list_2 PASSED                        [ 94%]
test_average.py::test_average_five_values PASSED                         [100%]

=================================== FAILURES ===================================
______________________ test_average_basic_1[values4-0.5] _______________________

values = (0, 10), expected = 0.5

    @pytest.mark.smoketest
    @pytest.mark.parametrize("values,expected", testdata)
    def test_average_basic_1(values, expected):
        """Otestování výpočtu průměru."""
        result = average(values)
>       assert result == expected, "Očekávaná hodnota {}, vráceno {}".format(expected, result)
E       AssertionError: Očekávaná hodnota 0.5, vráceno 5.0
E       assert 5.0 == 0.5
E         +5.0
E         -0.5

expected   = 0.5
result     = 5.0
values     = (0, 10)

test_average.py:29: AssertionError
__________________________ test_average_basic_2[0,10] __________________________

values = (0, 10), expected = 0.5

    @pytest.mark.smoketest
    @pytest.mark.parametrize("values,expected", testdata, ids=["1,1", "1,2", "0,1", "1,2,3", "0,10"])
    def test_average_basic_2(values, expected):
        """Otestování výpočtu průměru."""
        result = average(values)
>       assert result == expected, "Očekávaná hodnota {}, vráceno {}".format(expected, result)
E       AssertionError: Očekávaná hodnota 0.5, vráceno 5.0
E       assert 5.0 == 0.5
E         +5.0
E         -0.5

expected   = 0.5
result     = 5.0
values     = (0, 10)

test_average.py:37: AssertionError
______________________ test_average_basic_3[values4-0.5] _______________________

values = (0, 10), expected = 0.5

    @pytest.mark.smoketest
    @pytest.mark.parametrize(
        "values,expected",
        [
            pytest.param(
                (1, 1), 1
            ),
            pytest.param(
                (1, 2), 1.5
            ),
            pytest.param(
                (0, 1), 0.5
            ),
            pytest.param(
                (1, 2, 3), 2.0
            ),
            pytest.param(
                (0, 10), 0.5
            ),
            pytest.param(
                (), 0
            ),
        ],
    )
    def test_average_basic_3(values, expected):
        """Otestování výpočtu průměru."""
        result = average(values)
>       assert result == expected, "Očekávaná hodnota {}, vráceno {}".format(expected, result)
E       AssertionError: Očekávaná hodnota 0.5, vráceno 5.0
E       assert 5.0 == 0.5
E         +5.0
E         -0.5

expected   = 0.5
result     = 5.0
values     = (0, 10)

test_average.py:67: AssertionError
_______________________ test_average_basic_3[values5-0] ________________________

values = (), expected = 0

    @pytest.mark.smoketest
    @pytest.mark.parametrize(
        "values,expected",
        [
            pytest.param(
                (1, 1), 1
            ),
            pytest.param(
                (1, 2), 1.5
            ),
            pytest.param(
                (0, 1), 0.5
            ),
            pytest.param(
                (1, 2, 3), 2.0
            ),
            pytest.param(
                (0, 10), 0.5
            ),
            pytest.param(
                (), 0
            ),
        ],
    )
    def test_average_basic_3(values, expected):
        """Otestování výpočtu průměru."""
>       result = average(values)

expected   = 0
values     = ()

test_average.py:66: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
average.py:6: in average
    return f1(x)
        x          = ()
average.py:11: in f1
    return f2(x)
        x          = ()
average.py:16: in f2
    return f3(x)
        x          = ()
average.py:21: in f3
    return f4(x)
        x          = ()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = ()

    def f4(x):
        """Část špagetového kódu testovaného modulu."""
>       return sum(x)/float(len(x))
E       ZeroDivisionError: float division by zero

x          = ()

average.py:26: ZeroDivisionError
=========================== short test summary info ============================
FAILED test_average.py::test_average_basic_1[values4-0.5] - AssertionError: O...
FAILED test_average.py::test_average_basic_2[0,10] - AssertionError: Očekávan...
FAILED test_average.py::test_average_basic_3[values4-0.5] - AssertionError: O...
FAILED test_average.py::test_average_basic_3[values5-0] - ZeroDivisionError: ...
========================= 4 failed, 15 passed in 0.09s =========================
